package Game;

import java.awt.Color;

/**
 * @author arnaranjo
 * java foundations Project.
 */
public class Panel extends javax.swing.JFrame {

    @Override
    public void setTitle(String string) {
        super.setTitle(string);
    }
    
    gamePlay match;
    Thread gameThread;
    String gameName = "FollowMe";

    public Panel() {
        setTitle(gameName);
        initComponents();
        match = new gamePlay(btA, btB, btC, btD, btE, btF, btG, btH, btI, screen);
        btA.setBackground(Color.LIGHT_GRAY);
        btB.setBackground(Color.LIGHT_GRAY);
        btC.setBackground(Color.LIGHT_GRAY);
        btD.setBackground(Color.LIGHT_GRAY);
        btE.setBackground(Color.LIGHT_GRAY);
        btF.setBackground(Color.LIGHT_GRAY);
        btG.setBackground(Color.LIGHT_GRAY);
        btH.setBackground(Color.LIGHT_GRAY);
        btI.setBackground(Color.LIGHT_GRAY);
        screen.setText("Press Play! and try to follow the sequence...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGame = new javax.swing.JButton();
        btStop = new javax.swing.JButton();
        screen = new javax.swing.JLabel();
        btA = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        btF = new javax.swing.JButton();
        btG = new javax.swing.JButton();
        btH = new javax.swing.JButton();
        btI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btGame.setText("Start!");
        btGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGameActionPerformed(evt);
            }
        });

        btStop.setText("Stop / Reset");
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });

        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });

        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });

        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });

        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });

        btG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGActionPerformed(evt);
            }
        });

        btH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHActionPerformed(evt);
            }
        });

        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGame, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btStop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btG, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGame)
                    .addComponent(btStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGameActionPerformed
        screen.setText("");
        match.StopGame(false);
        gameThread = new Thread(match);
        gameThread.start();
    }//GEN-LAST:event_btGameActionPerformed

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed
        match.StopGame(true);
        match.setButtonControl(false);
        screen.setText("Press Play! and try to follow the sequence...");
    }//GEN-LAST:event_btStopActionPerformed

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(1);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {                    
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btAActionPerformed

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(2);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btBActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(3);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btCActionPerformed

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(4);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btDActionPerformed

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(5);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btEActionPerformed

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(6);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btFActionPerformed

    private void btGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(7);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btGActionPerformed

    private void btHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(8);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();
                }
            }
        }
    }//GEN-LAST:event_btHActionPerformed

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        if (match.getButtonControl()) {
            match.matchSequences.ExePlayer(9);
            if (match.matchSequences.PlayerSequenceSize() == match.getGameLevel()) {
                match.setButtonControl(false);
                if (match.Result()) {
                    gameThread = new Thread(match);
                    gameThread.start();                    
                }
            }
        }
    }//GEN-LAST:event_btIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btE;
    private javax.swing.JButton btF;
    private javax.swing.JButton btG;
    private javax.swing.JButton btGame;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btStop;
    private javax.swing.JLabel screen;
    // End of variables declaration//GEN-END:variables
}
